<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html.php</string>
	</array>
	<key>injections</key>
	<dict>
		<key>text.html.php - (meta.embedded | meta.tag), L:((text.html.php meta.tag) - (meta.embedded.block.php | meta.embedded.line.php)), L:(source.js - (meta.embedded.block.php | meta.embedded.line.php)), L:(source.css - (meta.embedded.block.php | meta.embedded.line.php))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#php-tag</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>HTML (PHP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>php-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?(?![^?]*\?&gt;)</string>
					<key>beginCaptures</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</array>
					<key>contentName</key>
					<string>source.php</string>
					<key>end</key>
					<string>(\?)&gt;</string>
					<key>endCaptures</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</array>
					<key>name</key>
					<string>meta.embedded.block.php</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.php</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?</string>
					<key>beginCaptures</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</array>
					<key>contentName</key>
					<string>source.php</string>
					<key>end</key>
					<string>(\?)&gt;</string>
					<key>endCaptures</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</array>
					<key>name</key>
					<string>meta.embedded.line.php</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.php</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.php</string>
	<key>uuid</key>
	<string>7A502A34-7BAD-45D2-9A0F-637F5341CA6F</string>
</dict>
</plist>
