<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html.php</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;?php</string>
	<key>injections</key>
	<dict>
		<key>R:text.html.php - (meta.embedded.block.php | comment)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=&lt;\?(php|=)?(?!\?&gt;))</string>
					<key>contentName</key>
					<string>meta.embedded.block.php</string>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;\?(php|=)?)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.begin.php</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.php</string>
							<key>end</key>
							<string>(\?)&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.php</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.php</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>name</key>
	<string>HTML (PHP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.php</string>
	<key>uuid</key>
	<string>7A502A34-7BAD-45D2-9A0F-637F5341CA6F</string>
</dict>
</plist>
